version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  chatapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: chatapp
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/ChatApp

volumes:
  mongo-data:
